# command line: main.py --config config/ucla/joint.yaml --model model.Hyperformer.Model --work-dir work_dir/ucla/Hyperformer_joint_9

base_lr: 0.1
batch_size: 16
config: config/ucla/joint.yaml
device: 0
ema: false
eval_interval: 5
feeder: feeders.feeder_ucla.Feeder
ignore_weights: []
joint_label: []
lambda_1: 0.0001
lambda_2: 0.1
log_interval: 100
lr_decay_rate: 0.1
lr_type: cosine
model: model.Hyperformer.Model
model_args:
  graph: graph.ucla.Graph
  graph_args:
    labeling_mode: spatial
  joint_label:
  - 0
  - 0
  - 0
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  num_class: 10
  num_person: 1
  num_point: 20
model_saved_name: ''
momentum: 0.9
nesterov: true
num_epoch: 150
num_worker: 48
optimizer: SGD
phase: train
print_log: true
resume: null
save_epoch: 10
save_interval: 1
save_score: false
seed: 1234
show_topk:
- 1
- 5
start_epoch: 0
step:
- 60
- 80
- 100
test_batch_size: 64
test_feeder_args:
  data_path: joint
  debug: false
  label_path: val
train_feeder_args:
  data_path: joint
  debug: false
  label_path: train
  normalization: false
  random_choose: true
  random_move: false
  random_shift: false
  window_size: 52
warm_up_epoch: 5
weight_decay: 0.0001
weights: null
work_dir: work_dir/ucla/Hyperformer_joint_9
